import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { signIn, useSession } from "next-auth/react";
import { useEffect } from "react";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const router = useRouter();
  const { data: session } = useSession();
  const usersQuery = api.user.findMany.useQuery();

  const createRoom = () => {
    const user = usersQuery?.data?.find(
      (user) => user.name === session?.user?.name
    );
    router.push(`/rooms/${user.id}`).catch(() => console.log("err"));
  };
  useEffect(() => {
    console.log("user", session?.user?.name);
    if (session?.user?.name) {
      createRoom();
    }
  }, [session]);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <button onClick={() => signIn()}>Sign in</button>
      </main>
    </>
  );
};

export default Home;
